HFP-2992 Adjust to meet design created after pull request
h5p/h5p-branching-scenario pull request #46
Opened 2021-01-22 22:29 UTC by otacke

- Move requiresFinishing setting in semantics.json
- Adjust path to requiresFinishing in view
- Add missing fields in translations

2021-01-25 10:09 UTC, simondate commented
Can you remove this please? https://github.com/otacke/h5p-branching-scenario/blob/HFP-2992-adjust-to-design/semantics.json#L228-L245

2021-01-25 10:30 UTC, simondate reviewed
Why aren't the changes consistent between all the different language files?

2021-01-25 11:00 UTC, simondate requested changes
I constantly get a breaking error when trying to press Proceed after completing a IV in the preview mode. Something to do with firing an xAPI statement that it can't handle. The error doesn't occur when viewing it normally.

![Screenshot 2021-01-25 at 11 58 23](https://user-images.githubusercontent.com/1676635/105697434-d69c2f80-5f04-11eb-9290-5282b5718ea8.png)

2021-01-25 11:25 UTC, otacke commented on language/.en.json
> +                "description": "Urges viewers to complete the interaction before proceeding with the scenario. This setting will only work for interactions that can be completed"
Just what the spec said ...

2021-01-25 12:04 UTC, otacke commented
> Can you remove this please? https://github.com/otacke/h5p-branching-scenario/blob/HFP-2992-adjust-to-design/semantics.json#L228-L245

@simondate Before I comment, please let me rest you assured that I know you just joined the band :-)

I can remove that, of course, but the whole idea of the pull-request (again: it was pre-qualified with Svein-Tore) was to provide a general solution that would work for any content type, not just IV and CP that just need some extra care because of the way they determine when a content is completed. It does. You can put in Fill-in-the-Blanks or whatever has a completed statement and you can prevent progression for those, too. The designs in HFP-2992 and HFP-2993 were created over half a year later than the pull request was filed (https://h5ptechnology.atlassian.net/browse/HFP-2830) and it's a pity that the pull request seems to have been ignored completely instead of taking in into consideration and working with it when creating the designs.

Now not only do we have this back and forth -- clearly, if pull-requests are handled that way it's more work and hassle than doing everything on your own -- but we're also antagonizing the people who funded this work back in the days. They needed that feature themselves, they asked whether it was fine to do it that way beforehand because they explicitly did not want to run a fork. And they will now be forced into one or they'll have to put in extra effort clean up the data structure of their contents. That's not a plus on business trustworthiness.

I guess I'll strip down my solution to an inferior one now ...

2021-01-25 13:43 UTC, otacke commented
@simondate I have no good answer for your question about the different language, because I am not sure which you mean in particular. I just had a look at semantics.json and .en.json and noticed differences, so even those have not been kept in sync and they were inconsistent even before merging in my changes. Since people usually base their new translations on .en.json, that may already have caused some diverging. Merging in my pull request may have introduced some more differences, because it was lying around for over a year and I didn't keep up with all the new language files and changes. Not sure if you rebased the pull request branch first or just merged in the changes. In the latter case, that may have overwritten some changes that had been done meanwhile.

AAAND sorry for my previous comment. The message holds, but I should not shoot messengers. Sorry again. I have removed the extra behavioral settings. That was indeed a leftover. I'll now go for the other changes related to the proceed button in CP and IV, move that around and silently keep the feature available for all the other content types for the future instead of removing it completely ;-)

2021-01-25 14:37 UTC, simondate commented on language/.en.json
> +                "description": "Urges viewers to complete the interaction before proceeding with the scenario. This setting will only work for interactions that can be completed"
I think Forces is the correct word to use here (as a native speaker). I'll get Jelena's second opinion.

2021-01-26 09:01 UTC, simondate requested changes
I've found that if you use IV and complete the content type and submit the score but then press "replay the video". You are unable to resubmit your score and continue with the course.

I don't know if we should design it so that when you submit and restart you are able to resubmit or if you are just rewatching the video (in which case we should have the proceed button in the top right like we do with CP). @jelenamilinovic what do you think?

2021-01-26 09:27 UTC, otacke reviewed
> I've found that if you use IV and complete the content type and submit the score but then press "replay the video". You are unable to resubmit your score and continue with the course.

@simondate Oh, you're absolutely right. That's the usual IV/submit screen behavior, but now that the proceed button has been moved into the overlay instead of being in the upper right corner, you cannot proceed anymore once you're out of interactions to complete (which will reset the submit button when completed one). Didn't think of that.

> I don't know if we should design it so that when you submit and restart you are able to resubmit or if you are just rewatching the video (in which case we should have the proceed button in the top right like we do with CP). @jelenamilinovic what do you think?

@Jelena I am also not sure what behavior would be best.

2021-01-26 09:27 UTC, otacke commented on scripts/libraryScreen.js
> +          this.wrapper.appendChild(self.overlay);
@simondate Well spotted. I missed that one when moving that stuff into a function.

2021-01-26 09:27 UTC, otacke commented on scripts/libraryScreen.js
> +        const feedbackScreen = this.createFeedbackScreen(self.libraryFeedback, this.nextLibraryId);
@simondate Okay, definitely should not have worked that late ...

2021-01-26 09:47 UTC, simondate commented on scripts/libraryScreen.js
> +        const feedbackScreen = this.createFeedbackScreen(self.libraryFeedback, this.nextLibraryId);
☕

2021-01-26 16:14 UTC, simondate approved these changes

2021-01-26 16:15 UTC, merged